<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;

class UserSeeder extends Seeder {
    public function run() {
        // run role seeder and permision seeder before run user seeder
        User::insert([
            [
                'id'            => '1',
                'first_name'    => 'Joshua',
                'last_name'     => 'Trinh',
                'is_admin'      => '1',
                'is_deleted'    => '0',
                'email'         => 'joshuatrinh5262@gmail.com',
                'password'      => Hash::make('123456789'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '2',
                'first_name'    => 'Truong',
                'last_name'     => 'Trinh',
                'is_admin'      => '1',
                'is_deleted'    => '0',
                'email'         => 'rokudo5262@gmail.com',
                'password'      => Hash::make('123456789'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '3',
                'first_name'    => 'Admin',
                'last_name'     => 'One',
                'is_admin'      => '1',
                'is_deleted'    => '0',
                'email'         => 'admin_1@gmail.com',
                'password'      => Hash::make('123456789'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '4',
                'first_name'    =>'Admin',
                'last_name'     =>'Two',
                'is_admin'      => '1',
                'is_deleted'    => '0',
                'email'         => 'admin_2@gmail.com',
                'password'      => Hash::make('123456789'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),   
            ],
            [
                'id'            => '5',
                'first_name'    =>'User',
                'last_name'     =>'Three',
                'is_admin'      => '0',
                'is_deleted'    => '0',
                'email'         => 'user_3@gmail.com',
                'password'      => Hash::make('123456789'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '6',
                'first_name'    => 'User',
                'last_name'     => 'Four',
                'is_admin'      => '0',
                'is_deleted'    => '0',
                'email'         => 'user_4@gmail.com',
                'password'      => Hash::make('123456789'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '7',
                'first_name'    => 'User',
                'last_name'     => 'five',
                'is_admin'      => '0',
                'is_deleted'    => '0',
                'email'         => 'user_5@gmail.com',
                'password'      => Hash::make('123456789'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '8',
                'first_name'    => 'User',
                'last_name'     => 'Six',
                'is_admin'      => '0',
                'is_deleted'    => '0',
                'email'         => 'user_6@gmail.com',
                'password'      => Hash::make('123456789'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '9',
                'first_name'    => 'User',
                'last_name'     => 'Seven',
                'is_admin'      => '0',
                'is_deleted'    => '0',
                'email'         => 'user_7@gmail.com',
                'password'      => Hash::make('123456789'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '10',
                'first_name'    => 'User',
                'last_name'     => 'Eight',
                'is_admin'      => '0',
                'is_deleted'    => '0',
                'email'         => 'user_8@gmail.com',
                'password'      => Hash::make('123456789'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '11',
                'first_name'    => 'User',
                'last_name '    => 'Nine',
                'is_admin'      => '0',
                'is_deleted'    => '0',
                'email'         => 'user_9@gmail.com',
                'password'      => Hash::make('123456789'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '12',
                'first_name'    => 'User',
                'last_name'     => 'Zero',
                'is_admin'      => '0',
                'is_deleted'    => '1',
                'email'         => 'user_0@gmail.com',
                'password'      => Hash::make('123456789'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '13',
                'first_name'    => 'User',
                'last_name'     => 'Ten',
                'is_admin'      => '0',
                'is_deleted'    => '1',
                'email'         => 'user_10@gmail.com',
                'password'      => Hash::make('123456789'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '14',
                'first_name'    => 'User',
                'last_name'     => 'Eleven',
                'is_admin'      => '0',
                'is_deleted'    => '1',
                'email'         => 'user_11@gmail.com',
                'password'      => Hash::make('123456789'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'id'            => '15',
                'first_name'    => 'User',
                'last_name'     => 'Twelve',
                'is_admin'      => '0',
                'is_deleted'    => '1',
                'email'         => 'user_12@gmail.com',
                'password'      => Hash::make('123456789'),
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
        ]);
    }
}
