/// <reference types="cypress" />
const url = 'http://127.0.0.1:8000/admin';
describe('Web URL', function() {
    it('check web url', function() {
        cy.visit('http://127.0.0.1:8000/admin/login')
        cy.get('input[type="email"]').type('joshuatrinh5262@gmail.com')
        cy.get('input[type="password"]').type('123456789')
        cy.get('.login-btn').click()
        //
        cy.visit('http://127.0.0.1:8000/admin/user')
        cy.contains('User List')
        cy.get('.delete-multiple-user-btn').should('have.disabled','disabled')
        cy.wait(500)
        cy.get('.create-new-user-btn').click()
        cy.wait(500)
        cy.contains('Create New User')
        cy.url().should('include', '/user/create') 
        cy.wait(500)
        cy.go('back')
        cy.wait(500)
        cy.get('.detail-user-btn').first().click()
        cy.wait(500)
        cy.contains('User Detail')
        cy.url().should('include', '/user/show') 
        cy.wait(500)
        cy.go('back')
        cy.wait(500)
        cy.get('.edit-user-btn').first().click()
        cy.wait(500)
        cy.contains('User Update')
        cy.url().should('include', '/user/edit') 
        cy.wait(500)
        cy.go('back')
        cy.wait(500)
        cy.get('.back-btn').click()
        cy.wait(500)
        cy.url().should('eq',url)
    })
  })